import { DataSourceNote, TransitEdge, TransitNode } from "../types/transit";

const createBidirectionalEdge = (
  slug: string,
  edge: Omit<TransitEdge, "id">,
): TransitEdge[] => [
  {
    ...edge,
    id: `${slug}-forward`,
  },
  {
    ...edge,
    id: `${slug}-reverse`,
    from: edge.to,
    to: edge.from,
  },
];

export const transitNodes: TransitNode[] = [
  {
    id: "kengeri",
    name: "Kengeri",
    kind: "metro",
    lat: 12.9159,
    lng: 77.4831,
    zone: "West Bengaluru",
    demandScore: 52,
    description: "Residential western gateway into the Purple Line corridor.",
    modes: ["metro"],
    aliases: ["Kengeri Metro"],
  },
  {
    id: "mysore-road",
    name: "Mysore Road",
    kind: "metro",
    lat: 12.9467,
    lng: 77.5301,
    zone: "West Bengaluru",
    demandScore: 58,
    description: "Strong feeder station for the southwest bus corridor.",
    modes: ["metro"],
    aliases: ["Mysore Road Metro"],
  },
  {
    id: "vijayanagar",
    name: "Vijayanagar",
    kind: "metro",
    lat: 12.9619,
    lng: 77.5398,
    zone: "Central West",
    demandScore: 61,
    description: "Dense residential catchment with quick access to Majestic.",
    modes: ["metro"],
    aliases: ["Vijayanagar Metro"],
  },
  {
    id: "majestic",
    name: "Kempegowda Majestic",
    kind: "interchange",
    lat: 12.9763,
    lng: 77.5713,
    zone: "City Core",
    demandScore: 100,
    description: "The biggest interchange linking metro lines and long-range bus services.",
    modes: ["metro", "bus"],
    aliases: ["Majestic", "Kempegowda", "Kempegowda Bus Station"],
  },
  {
    id: "cubbon-park",
    name: "Cubbon Park",
    kind: "metro",
    lat: 12.9812,
    lng: 77.5966,
    zone: "CBD",
    demandScore: 65,
    description: "Fast CBD connector between Majestic and MG Road.",
    modes: ["metro"],
    aliases: ["Cubbon Park Metro"],
  },
  {
    id: "mg-road",
    name: "MG Road",
    kind: "interchange",
    lat: 12.9755,
    lng: 77.6068,
    zone: "CBD East",
    demandScore: 82,
    description: "Key interchange between eastbound metro riders and CBD buses.",
    modes: ["metro", "bus"],
    aliases: ["Mahatma Gandhi Road", "MG Road Metro"],
  },
  {
    id: "indiranagar",
    name: "Indiranagar",
    kind: "interchange",
    lat: 12.9783,
    lng: 77.6387,
    zone: "East Bengaluru",
    demandScore: 71,
    description: "Busy mixed-use area with strong bus and metro demand.",
    modes: ["metro", "bus"],
    aliases: ["Indiranagar Metro"],
  },
  {
    id: "baiyappanahalli",
    name: "Baiyappanahalli",
    kind: "interchange",
    lat: 12.9907,
    lng: 77.6525,
    zone: "East Bengaluru",
    demandScore: 75,
    description: "Primary east-side transfer point feeding Whitefield and KR Puram.",
    modes: ["metro", "bus"],
    aliases: ["Baiyappanahalli Metro"],
  },
  {
    id: "kr-puram",
    name: "KR Puram",
    kind: "interchange",
    lat: 12.996,
    lng: 77.6962,
    zone: "Outer East",
    demandScore: 73,
    description: "Bridge node between metro demand and outer-ring road buses.",
    modes: ["metro", "bus"],
    aliases: ["K R Puram", "Krishnarajapuram"],
  },
  {
    id: "whitefield",
    name: "Whitefield",
    kind: "interchange",
    lat: 12.995,
    lng: 77.7611,
    zone: "Far East",
    demandScore: 70,
    description: "Office-heavy eastern hub with strong peak-hour commuting demand.",
    modes: ["metro", "bus"],
    aliases: ["Kadugodi", "Kadugodi Tree Park", "Whitefield Metro"],
  },
  {
    id: "yeshwanthpur",
    name: "Yeshwanthpur",
    kind: "interchange",
    lat: 13.0234,
    lng: 77.5502,
    zone: "North West",
    demandScore: 67,
    description: "Northern gateway with rail and bus interchange value.",
    modes: ["metro", "bus"],
    aliases: ["Yeshwanthpur Metro"],
  },
  {
    id: "sandal-soap-factory",
    name: "Sandal Soap Factory",
    kind: "metro",
    lat: 13.0141,
    lng: 77.5538,
    zone: "North West",
    demandScore: 48,
    description: "Green Line connector serving industrial and residential pockets.",
    modes: ["metro"],
    aliases: ["Sandal Soap Factory Metro"],
  },
  {
    id: "rajajinagar",
    name: "Rajajinagar",
    kind: "metro",
    lat: 12.9918,
    lng: 77.5567,
    zone: "North Central",
    demandScore: 57,
    description: "Strong residential station with a dependable metro catchment.",
    modes: ["metro"],
    aliases: ["Rajajinagar Metro"],
  },
  {
    id: "mantri-square",
    name: "Mantri Square",
    kind: "metro",
    lat: 12.9915,
    lng: 77.5706,
    zone: "North Central",
    demandScore: 63,
    description: "Dense retail and workday demand just north of Majestic.",
    modes: ["metro"],
    aliases: ["Sampige Road", "Mantri Square Sampige Road"],
  },
  {
    id: "chikpete",
    name: "Chikpete",
    kind: "interchange",
    lat: 12.969,
    lng: 77.5743,
    zone: "Market Core",
    demandScore: 64,
    description: "Market district stop with strong short-hop transfer demand.",
    modes: ["metro", "bus"],
    aliases: ["Chickpet", "Chickpete"],
  },
  {
    id: "national-college",
    name: "National College",
    kind: "metro",
    lat: 12.9576,
    lng: 77.573,
    zone: "South Central",
    demandScore: 59,
    description: "Green Line stop feeding Basavanagudi and nearby institutions.",
    modes: ["metro"],
    aliases: ["National College Metro"],
  },
  {
    id: "lalbagh",
    name: "Lalbagh",
    kind: "metro",
    lat: 12.9504,
    lng: 77.5849,
    zone: "South Central",
    demandScore: 60,
    description: "Popular southbound stop serving commercial and civic trips.",
    modes: ["metro"],
    aliases: ["Lalbagh Metro"],
  },
  {
    id: "jayanagar",
    name: "Jayanagar",
    kind: "interchange",
    lat: 12.9293,
    lng: 77.5826,
    zone: "South Bengaluru",
    demandScore: 68,
    description: "Dense mixed-use district with strong metro and feeder movement.",
    modes: ["metro", "bus"],
    aliases: ["Jayanagar Metro"],
  },
  {
    id: "banashankari",
    name: "Banashankari",
    kind: "interchange",
    lat: 12.9241,
    lng: 77.5736,
    zone: "South Bengaluru",
    demandScore: 72,
    description: "Important southern interchange linking green-line riders and buses.",
    modes: ["metro", "bus"],
    aliases: ["Banashankari Metro"],
  },
  {
    id: "silk-board",
    name: "Silk Board",
    kind: "bus",
    lat: 12.9177,
    lng: 77.6238,
    zone: "South East",
    demandScore: 92,
    description: "One of Bengaluru's busiest bus-heavy commuter choke points.",
    modes: ["bus"],
    aliases: ["Silk Board Junction"],
  },
  {
    id: "koramangala",
    name: "Koramangala",
    kind: "place",
    lat: 12.9352,
    lng: 77.6245,
    zone: "South East",
    demandScore: 78,
    description: "Work and lifestyle district with high inter-neighbourhood demand.",
    modes: ["bus", "walk"],
    aliases: ["Koramangala 5th Block", "Koramangala 6th Block"],
  },
  {
    id: "hsr-layout",
    name: "HSR Layout",
    kind: "place",
    lat: 12.9116,
    lng: 77.6474,
    zone: "South East",
    demandScore: 69,
    description: "Feeder neighbourhood requiring strong bus connectors to the network.",
    modes: ["bus", "walk"],
    aliases: ["HSR", "H.S.R Layout"],
  },
  {
    id: "marathahalli",
    name: "Marathahalli",
    kind: "bus",
    lat: 12.9591,
    lng: 77.6974,
    zone: "Outer East",
    demandScore: 80,
    description: "Major ring-road interchange with dense office traffic.",
    modes: ["bus"],
    aliases: ["Marathalli", "Marathahalli Bridge"],
  },
  {
    id: "hebbal",
    name: "Hebbal",
    kind: "bus",
    lat: 13.0356,
    lng: 77.597,
    zone: "North Bengaluru",
    demandScore: 77,
    description: "Northbound highway gateway connecting city trips to airport buses.",
    modes: ["bus"],
    aliases: ["Hebbal Flyover"],
  },
  {
    id: "airport",
    name: "Kempegowda Airport",
    kind: "place",
    lat: 13.1986,
    lng: 77.7066,
    zone: "Airport Corridor",
    demandScore: 66,
    description: "Long-haul trip destination currently dominated by bus-based access.",
    modes: ["bus", "walk"],
    aliases: ["Bengaluru Airport", "BLR Airport", "KIA"],
  },
  {
    id: "electronic-city",
    name: "Electronic City",
    kind: "place",
    lat: 12.8456,
    lng: 77.6603,
    zone: "South Corridor",
    demandScore: 74,
    description: "Large employment cluster that depends on strong feeder connectivity.",
    modes: ["bus", "walk"],
    aliases: ["E City", "Electronic City Phase 1"],
  },
];

export const transitEdges: TransitEdge[] = [
  ...createBidirectionalEdge("purple-kengeri-mysore", {
    from: "kengeri",
    to: "mysore-road",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 8,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("purple-mysore-vijayanagar", {
    from: "mysore-road",
    to: "vijayanagar",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 7,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("purple-vijayanagar-majestic", {
    from: "vijayanagar",
    to: "majestic",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 9,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("purple-majestic-cubbon", {
    from: "majestic",
    to: "cubbon-park",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 6,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.95,
  }),
  ...createBidirectionalEdge("purple-cubbon-mg", {
    from: "cubbon-park",
    to: "mg-road",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 4,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.95,
  }),
  ...createBidirectionalEdge("purple-mg-indiranagar", {
    from: "mg-road",
    to: "indiranagar",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 8,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("purple-indiranagar-baiyappanahalli", {
    from: "indiranagar",
    to: "baiyappanahalli",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 7,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("purple-baiyappanahalli-krpuram", {
    from: "baiyappanahalli",
    to: "kr-puram",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 9,
    headwayMinutes: 6,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.93,
  }),
  ...createBidirectionalEdge("purple-krpuram-whitefield", {
    from: "kr-puram",
    to: "whitefield",
    mode: "metro",
    line: "Purple Line",
    travelMinutes: 17,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.92,
  }),
  ...createBidirectionalEdge("green-yeshwanthpur-sandal", {
    from: "yeshwanthpur",
    to: "sandal-soap-factory",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 3,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-sandal-rajajinagar", {
    from: "sandal-soap-factory",
    to: "rajajinagar",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 4,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-rajajinagar-mantri", {
    from: "rajajinagar",
    to: "mantri-square",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 4,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-mantri-majestic", {
    from: "mantri-square",
    to: "majestic",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 4,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.95,
  }),
  ...createBidirectionalEdge("green-majestic-chikpete", {
    from: "majestic",
    to: "chikpete",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 3,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.95,
  }),
  ...createBidirectionalEdge("green-chikpete-national", {
    from: "chikpete",
    to: "national-college",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 4,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-national-lalbagh", {
    from: "national-college",
    to: "lalbagh",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 3,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-lalbagh-jayanagar", {
    from: "lalbagh",
    to: "jayanagar",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 4,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("green-jayanagar-banashankari", {
    from: "jayanagar",
    to: "banashankari",
    mode: "metro",
    line: "Green Line",
    travelMinutes: 6,
    headwayMinutes: 7,
    firstDeparture: "05:00",
    lastDeparture: "23:00",
    reliability: 0.94,
  }),
  ...createBidirectionalEdge("bus-500d-hebbal-mg", {
    from: "hebbal",
    to: "mg-road",
    mode: "bus",
    line: "500D",
    travelMinutes: 22,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:45",
    reliability: 0.83,
  }),
  ...createBidirectionalEdge("bus-500d-mg-marathahalli", {
    from: "mg-road",
    to: "marathahalli",
    mode: "bus",
    line: "500D",
    travelMinutes: 30,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:45",
    reliability: 0.8,
  }),
  ...createBidirectionalEdge("bus-500d-marathahalli-whitefield", {
    from: "marathahalli",
    to: "whitefield",
    mode: "bus",
    line: "500D",
    travelMinutes: 24,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:45",
    reliability: 0.79,
  }),
  ...createBidirectionalEdge("bus-kia8-majestic-hebbal", {
    from: "majestic",
    to: "hebbal",
    mode: "bus",
    line: "KIA-8",
    travelMinutes: 25,
    headwayMinutes: 20,
    firstDeparture: "04:45",
    lastDeparture: "23:45",
    reliability: 0.88,
  }),
  ...createBidirectionalEdge("bus-kia8-hebbal-airport", {
    from: "hebbal",
    to: "airport",
    mode: "bus",
    line: "KIA-8",
    travelMinutes: 32,
    headwayMinutes: 20,
    firstDeparture: "04:45",
    lastDeparture: "23:45",
    reliability: 0.9,
  }),
  ...createBidirectionalEdge("bus-500a-silk-marathahalli", {
    from: "silk-board",
    to: "marathahalli",
    mode: "bus",
    line: "500A",
    travelMinutes: 18,
    headwayMinutes: 10,
    firstDeparture: "05:30",
    lastDeparture: "22:30",
    reliability: 0.81,
  }),
  ...createBidirectionalEdge("bus-v500c-silk-koramangala", {
    from: "silk-board",
    to: "koramangala",
    mode: "bus",
    line: "V500C",
    travelMinutes: 10,
    headwayMinutes: 8,
    firstDeparture: "05:30",
    lastDeparture: "22:30",
    reliability: 0.84,
  }),
  ...createBidirectionalEdge("bus-v500c-koramangala-mg", {
    from: "koramangala",
    to: "mg-road",
    mode: "bus",
    line: "V500C",
    travelMinutes: 20,
    headwayMinutes: 8,
    firstDeparture: "05:30",
    lastDeparture: "22:30",
    reliability: 0.83,
  }),
  ...createBidirectionalEdge("bus-201r-koramangala-indiranagar", {
    from: "koramangala",
    to: "indiranagar",
    mode: "bus",
    line: "201R",
    travelMinutes: 20,
    headwayMinutes: 10,
    firstDeparture: "05:45",
    lastDeparture: "22:00",
    reliability: 0.8,
  }),
  ...createBidirectionalEdge("bus-335e-majestic-koramangala", {
    from: "majestic",
    to: "koramangala",
    mode: "bus",
    line: "335E",
    travelMinutes: 24,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:15",
    reliability: 0.8,
  }),
  ...createBidirectionalEdge("bus-335e-koramangala-hsr", {
    from: "koramangala",
    to: "hsr-layout",
    mode: "bus",
    line: "335E",
    travelMinutes: 12,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:15",
    reliability: 0.79,
  }),
  ...createBidirectionalEdge("bus-335e-hsr-ecity", {
    from: "hsr-layout",
    to: "electronic-city",
    mode: "bus",
    line: "335E",
    travelMinutes: 18,
    headwayMinutes: 12,
    firstDeparture: "05:30",
    lastDeparture: "22:15",
    reliability: 0.77,
  }),
  ...createBidirectionalEdge("bus-356c-silk-ecity", {
    from: "silk-board",
    to: "electronic-city",
    mode: "bus",
    line: "356C",
    travelMinutes: 22,
    headwayMinutes: 10,
    firstDeparture: "05:30",
    lastDeparture: "22:30",
    reliability: 0.8,
  }),
  ...createBidirectionalEdge("bus-201m-banashankari-silk", {
    from: "banashankari",
    to: "silk-board",
    mode: "bus",
    line: "201M",
    travelMinutes: 24,
    headwayMinutes: 10,
    firstDeparture: "05:45",
    lastDeparture: "22:00",
    reliability: 0.79,
  }),
  ...createBidirectionalEdge("bus-v521-krpuram-marathahalli", {
    from: "kr-puram",
    to: "marathahalli",
    mode: "bus",
    line: "V521",
    travelMinutes: 14,
    headwayMinutes: 9,
    firstDeparture: "05:45",
    lastDeparture: "22:15",
    reliability: 0.82,
  }),
  ...createBidirectionalEdge("walk-hsr-silk", {
    from: "hsr-layout",
    to: "silk-board",
    mode: "walk",
    line: "Walk Connector",
    travelMinutes: 11,
    headwayMinutes: 0,
    firstDeparture: "00:00",
    lastDeparture: "23:59",
    reliability: 0.98,
  }),
  ...createBidirectionalEdge("walk-koramangala-silk", {
    from: "koramangala",
    to: "silk-board",
    mode: "walk",
    line: "Walk Connector",
    travelMinutes: 14,
    headwayMinutes: 0,
    firstDeparture: "00:00",
    lastDeparture: "23:59",
    reliability: 0.98,
  }),
];

export const dataSourceNotes: DataSourceNote[] = [
  {
    label: "Bengaluru Open Data",
    url: "https://opendata.benscl.com/",
    description:
      "Reference portal for official Bengaluru civic and metro-related open datasets.",
  },
  {
    label: "Namma Metro GeoJSON",
    url: "https://github.com/geohacker/namma-metro",
    description:
      "Open-source geometry reference used to shape station positioning and corridor structure.",
  },
  {
    label: "BMTC GTFS Reference",
    url: "https://github.com/Vonter/bmtc-gtfs",
    description:
      "Open-source BMTC GTFS-style feed reference for future bus-network expansion.",
  },
];

export const DEFAULT_ORIGIN = "Koramangala";
export const DEFAULT_DESTINATION = "Whitefield";

